### ISSUE TITLE
 Integrate with Zoom

### ISSUE THREAD

**Issue by serdiukov-o-nordwhale** [GoodDollar/FaceVerification#5]
We're using now Zoom for face verification on web.
So, react-native-web-facecapture should on native apps for now
I've added some stubs which prevents to use it on web
Also there were a few lint erros whicxh were fixed

**Comment by serdiukov-o-nordwhale** [comment]
@yaroslav-fedyshyn-nordwhale Please review an PR and check how it works with GoodApp. If there will be some errors - pls fix them.
Ask me if something is unclear

**Comment by sirpy** [comment]
@serdiukov-o-nordwhale connect it to the PR
when can you merge?
